
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saief
 */
public class updateaccount extends javax.swing.JFrame {

  connection c=new connection();  Connection conn; Statement stmt,stmt2,stmt3; ResultSet rs,rs3; String  type; int id;
 String uname;
    public updateaccount(int id,String uname) throws SQLException {
        
        
        
        initComponents();
        this.id=id;
    
        System.out.println(uname);
        conn=c.conn;
        stmt=conn.createStatement();
        stmt2=conn.createStatement();
        rs=stmt.executeQuery("select * from customers where cin="+id); rs.next();
        
        if (rs.getRow()==1) {
            name.setText("Welcome "+rs.getString("firstname")+" "+rs.getString("lastname"));
            type="customer";
            customer.setVisible(true);
            bank.setVisible(false);
        }
        else  {
            rs=stmt.executeQuery("select * from banks where bankid="+id);
            rs.next();
                    if (rs.getRow()==1) {
                        name.setText("Welcome "+rs.getString("bankname")+" Administrator");
                 type="bank";
            customer.setVisible(false);
            bank.setVisible(true);
            }
            
           rs.close();
            
        }
   }

   

     
    
    
    
    
    
    
    
    
    




   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        customer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerfirstname = new javax.swing.JTextField();
        customerlastname = new javax.swing.JTextField();
        customerusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        customerpassword = new javax.swing.JPasswordField();
        customerconfirmpassword = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        bank = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        bankname = new javax.swing.JTextField();
        bankusername = new javax.swing.JTextField();
        interest = new javax.swing.JTextField();
        bankpassword = new javax.swing.JPasswordField();
        bankpasswordconfirm = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("New Password");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Verify Passowrd");

        customerfirstname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerfirstnameActionPerformed(evt);
            }
        });

        customerlastname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        customerusername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        customerusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerusernameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Change Last Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Change ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Change First Name");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerLayout = new javax.swing.GroupLayout(customer);
        customer.setLayout(customerLayout);
        customerLayout.setHorizontalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(40, 40, 40))
                        .addGroup(customerLayout.createSequentialGroup()
                            .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerusername, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(150, 150, 150))
        );

        customerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {customerconfirmpassword, customerfirstname, customerlastname, customerpassword, customerusername});

        customerLayout.setVerticalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(customerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(customerconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(55, 55, 55))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Change Bank Name");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Change username");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Change Interest Rate");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Change Password");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Confirm Password");

        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setText("Change Bankname");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setText("Change Username");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("Change Interest rate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setText("Change Password");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton10.setText("Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bankLayout = new javax.swing.GroupLayout(bank);
        bank.setLayout(bankLayout);
        bankLayout.setHorizontalGroup(
            bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankLayout.createSequentialGroup()
                .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankLayout.createSequentialGroup()
                        .addComponent(bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(bankLayout.createSequentialGroup()
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankpasswordconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(bankLayout.createSequentialGroup()
                        .addComponent(bankusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(bankLayout.createSequentialGroup()
                        .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(120, 120, 120))
        );

        bankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bankname, bankpassword, bankpasswordconfirm, bankusername, interest});

        bankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton5, jButton6, jButton7, jButton8});

        bankLayout.setVerticalGroup(
            bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bankLayout.createSequentialGroup()
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bankusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bankLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addGap(15, 15, 15)
                .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankLayout.createSequentialGroup()
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bankpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bankpasswordconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bankLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(32, 32, 32)
                        .addComponent(jButton8)))
                .addGap(31, 31, 31)
                .addComponent(jButton10)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(name)
                .addGap(259, 259, 259))
            .addComponent(customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 88, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerfirstnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select firstname from customers where cin="+id);
          rs3.next();
          
              if (customerfirstname.getText().equals(rs3.getString("firstname")) || customerfirstname.getText().length()==0 ) {
            JOptionPane.showMessageDialog(this,"Enter a valid new firstname",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update customers set username='"+customerfirstname.getText()+"' where cin="+id)==1) {
              JOptionPane.showMessageDialog(this,"First name updated Scussfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
      try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select username from customers where cin="+id);
          rs3.next();
          
              if (customerusername.getText().equals(rs3.getString("username")) || customerusername.getText().length()==0  ) {
            JOptionPane.showMessageDialog(this,"Enter a new valid username",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update customers set username='"+customerusername.getText()+"' where cin="+id)==1) {
              JOptionPane.showMessageDialog(this,"Username updated Scussfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed
            
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        
           try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select password from customers where cin="+id);
          rs3.next();
          
              if (new String(customerpassword.getPassword()).equals(rs3.getString("password"))  ) {
            JOptionPane.showMessageDialog(this,"Enter a new Password",null,JOptionPane.ERROR_MESSAGE);
              } 
              else {
        
        
                  if (  (!new String (customerpassword.getPassword()).equals(new String(customerconfirmpassword.getPassword())))  || 
                     customerpassword.getPassword().length==0    ||    customerconfirmpassword.getPassword().length==0                      )
                          {
                      JOptionPane.showMessageDialog(this,"Passwords do not match/ are null",null,JOptionPane.ERROR_MESSAGE);
                          }                 
         else {
                      if (stmt2.executeUpdate("update customers set password='"+new String(customerpassword.getPassword())+"' where cin="+id)==1) {
                          JOptionPane.showMessageDialog(this,"Password updated Scussfully");
                      }
                  }                    
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }  
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select bankname from banks where bankid="+id);
          rs3.next();
          
              if (bankname.getText().equals(rs3.getString("bankname")) || bankname.getText().length()==0 ) {
            JOptionPane.showMessageDialog(this,"Enter a valid new bankname",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update banks set bankname='"+bankname.getText()+"' where bankid="+id)==1) {
              JOptionPane.showMessageDialog(this,"Bank updated Sucessfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }          
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 
   
      try {
              rs=stmt.executeQuery("select * from customers where cin="+id);
              rs.next();
          new customer(rs.getString("firstname")+" "+rs.getString("lastname"),id).setVisible(true);    
          dispose();
          
      } catch (SQLException | NumberFormatException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select lastname from customers where cin="+id);
          rs3.next();
          
              if (customerlastname.getText().equals(rs3.getString("lastname")) || customerlastname.getText().length()==0  ) {
            JOptionPane.showMessageDialog(this,"Enter a new Last Name",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update customers set lastname='"+customerlastname.getText()+"' where cin="+id)==1) {
              JOptionPane.showMessageDialog(this,"Last name updated Scussfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select password from banks where bankid="+id);
          rs3.next();
          
              if (new String(bankpassword.getPassword()).equals(rs3.getString("password"))  ) {
            JOptionPane.showMessageDialog(this,"Enter a new Password",null,JOptionPane.ERROR_MESSAGE);
              } 
              else {
        
        
                  if (  (!new String (bankpassword.getPassword()).equals(new String(bankpasswordconfirm.getPassword())))  || 
                     bankpassword.getPassword().length==0    ||    bankpasswordconfirm.getPassword().length==0                      )
                          {
                      JOptionPane.showMessageDialog(this,"Passwords do not match/ are null",null,JOptionPane.ERROR_MESSAGE);
                          }                 
         else {
                      if (stmt2.executeUpdate("update banks set password='"+new String(bankpassword.getPassword())+"' where bankid="+id)==1) {
                          JOptionPane.showMessageDialog(this,"Password updated Scussfully");
                      }
                  }                    
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
              rs=stmt.executeQuery("select * from banks where bankid="+id);
              rs.next();
          new customer(rs.getString("bankname"),id).setVisible(true);    
          dispose();
          
      } catch (SQLException | NumberFormatException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void customerusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerusernameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select username from banks where bankid="+id);
          rs3.next();
          
              if (bankusername.getText().equals(rs3.getString("username")) || bankusername.getText().length()==0  ) {
            JOptionPane.showMessageDialog(this,"Enter a new valid username",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update banks set username='"+bankusername.getText()+"' where bankid="+id)==1) {
              JOptionPane.showMessageDialog(this,"Username updated Scussfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          try {
           stmt3=conn.createStatement();
           rs3=stmt3.executeQuery("select interest from banks where bankid="+id);
          rs3.next();
          
              if (interest.getText().equals(rs3.getString("interest")) || interest.getText().length()==0  ) {
            JOptionPane.showMessageDialog(this,"Enter a valid interest rate",null,JOptionPane.ERROR_MESSAGE);
              }
              else {
        
        
          if (stmt2.executeUpdate("update banks set interest='"+interest.getText()+"' where bankid="+id)==1) {
              JOptionPane.showMessageDialog(this,"Interest rate updated Scussfully");
          }
      }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(updateaccount.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bank;
    private javax.swing.JTextField bankname;
    private javax.swing.JPasswordField bankpassword;
    private javax.swing.JPasswordField bankpasswordconfirm;
    private javax.swing.JTextField bankusername;
    private javax.swing.JPanel customer;
    private javax.swing.JPasswordField customerconfirmpassword;
    private javax.swing.JTextField customerfirstname;
    private javax.swing.JTextField customerlastname;
    private javax.swing.JPasswordField customerpassword;
    private javax.swing.JTextField customerusername;
    private javax.swing.JTextField interest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
